### PR TITLE
PASS Support Services standalone

### PR DESCRIPTION
**Pull request by sdreher**
migrating pageblock client-side interactive to webpack architecture

### CODE REVIEW

**Comment by sdreher** [comment]
testing webhook

**Comment by nikolas** [comment]
I get some errors when I run `make build`:
http://dpaste.com/3292H9K

Using node.js 4.2.6 / npm 3.9.0. The `dist/bundle.js` file does get created.. it's the only thing in the dist directory, is that the correct behavior? Then when I open index.html, I get this error so I think there was a problem somewhere:

> Uncaught Error: Cannot find module "../fonts/glyphicons-halflings-regular.eot"

**Comment by sdreher** [comment]
The errors indicate that the file-loader dependency is needed. I've added this to the package.json. Oddly, I'm not seeing this in my dev environment.

**Comment by nikolas** [comment]
Cool, it works in my environment now

**Pull request merged**
